# Generated by Django 2.2.10 on 2021-01-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateField(),
        ),
    ]
