# Generated by Django 2.2.10 on 2021-01-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210129_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertracker',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answertracker',
            name='choice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Choice'),
        ),
    ]
